language: python

sudo: false

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

matrix:
 include:
  - python: 3.6
    env: TOXENV=i18n

install:
 - pip install tox tox-travis

script:
 - tox
